[package]
name = "lscp"
authors = ["Leonardo Pennino"]
version = "0.1.0"
edition = "2021"
description = "LSCP (Leonardo stupid communication protocol) is an application designed to allow communication between a java instance  and a gramine process running in SGX"

[features]
sgx = []

[[bin]]
name = "server"
path = "src/bin/server/main.rs"

[lib]
name = "rust_ta"


[dependencies]
anyhow = "1.0.89"
axum = { version = "0.7.6", features = ["json"] }
axum-server = { version = "0.7.1", features = ["rustls", "tls-rustls"] }
nix = { version = "0.29.0", features = ["fs"] }
rustix = { version = "0.38.37", features = ["fs", "pipe"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tempfile = "3.12.0"
tokio = { version = "1.40.0", features = ["full"] }
ra_tls = { path = "../ra-tls" ,  features=["sgx"]}
rcgen = "0.13.1"
reqwest = "0.12.9"
thiserror = "2.0.3"
ring = "0.17.8"
base64 = "0.22.1"
toml = "0.8.19"
chrono = "0.4.38"
jwt = "0.16.0"
uuid = { version = "1.11.0", features = ["serde", "v4"] }
axum-test = "16.4.0"
clap = { version = "4.5.26", features = ["derive"] }
