mr_enclave = "asd"
[[users]]
capabilities = ["READ"]
pubkey = "MIIBCgKCAQEAvXnE12yLGgLiP3A+JR4kTwKNzbRjAAYtb004+trGmKRUiXRKzsiaabeVXxMVM3wC6ft7CTlcQPQOqrnZsPCzGEjsPPLpzddWj96JwIV1jEGyteTSpUBc0whKnkxjLVX+Y+sjOF1pREiGLVnMf2IQlZVh2VoGU9ptGOsNkie4mwAamyPFKqTstT+ifwhQunX8W57bMCT5CetUjkIBqxHCeTM8G3YJHY65kseWVcOm3MHDdyBHT10wGQcxkI8Hzw+8A73fJk72ocyeXX8dqD8rvy8YZf44ZK+GkPPNIGyxq1GnpKE1NOSXD0IdFlD26ALBYPENOMw5q0F3qCoxC3TwbwIDAQAB"
